[package]
name = "chrono-simpletz"
version = "0.1.0"
authors = ["aobatact <aobatact144@gmail.com>"]
edition = "2018"
build = "build.rs"
description = "Simple Zero Sized Typed Utc timezones for chrono"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", default-features = false }

