[package]
name = "chrono-simpletz"
version = "0.1.2"
authors = ["aobatact <aobatact144@gmail.com>"]
edition = "2018"
build = "build.rs"
description = "Simple Zero Sized Typed Utc timezones for chrono"
license = "MIT"
keywords = ["time", "timezone"]
repository = "https://github.com/aobatact/chrono_simpletz"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["std","clock","serde"]
std = []
clock = ["chrono/clock"]
serde = ["serde1","chrono/serde","serde_with"]

[dependencies]
chrono = { version = "0.4", default-features = false }

[dependencies.serde1]
default-features = false
optional = true
version = "1.0.99"
package = "serde"

[dependencies.serde_with]
default-features = false
optional = true
version = "1.8.0"

